### ISSUE TITLE
Taken email address 

### ISSUE THREAD

**Issue by w00fz** [oldgit777/grav#1]
Hello @oldgit777 
I'm the author of the GitSync plugin and I'm happy to see you trying it out, hope it's of your liking!

I noticed that you have added the email `gitsync@getgrav.org` to your account which is now affecting everyone who uses gitsync as it appears like you are making those commits.

Could you please release that email? You won't be able to verify it anyway. I have also just released a new version of GitSync to work around this problem but I would like to associate it to the main account.

You can go to https://github.com/settings/emails and click on the trash bin of the `gitsync@getgrav.org` email.

Thank you!

**Comment by oldgit777** [comment]
Hi, Djamil

I haven't added the email.
I guess it was picked up from the plugin as  gitsync.grav.org was in one of
the advanced fields.
I didn't know I had to change this.
I've deleted it from my github account.
I'm not seeing a new version available in my admin panel?

og

**Comment by w00fz** [comment]
Thank you @oldgit777 for understanding and removing the email. Looks all good now!
The new update should be available, version 1.0.1, try going in the dashboard and click the check for updates button, you should see it there.
